import { sql } from "drizzle-orm";
import { index, integer, real, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const observers = sqliteTable("observers", { id: integer("id").primaryKey({ autoIncrement: true }), name: text("name").notNull().unique(), active: integer("active", { mode: "boolean" }).notNull().default(true), isAdmin: integer("is_admin", { mode: "boolean" }).notNull().default(false) });
export const authSessions = sqliteTable("auth_sessions", { tokenHash: text("token_hash").primaryKey(), observerId: integer("observer_id").notNull().references(() => observers.id), expiresAt: text("expires_at").notNull(), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`) }, (t) => [index("idx_auth_sessions_observer_id").on(t.observerId), index("idx_auth_sessions_expires_at").on(t.expiresAt)]);
export const species = sqliteTable("species", { id: integer("id").primaryKey({ autoIncrement: true }), commonName: text("common_name").notNull().unique(), scientificName: text("scientific_name").notNull().default(""), active: integer("active", { mode: "boolean" }).notNull().default(true) });
export const sightings = sqliteTable("sightings", {
  id: integer("id").primaryKey({ autoIncrement: true }), observerId: integer("observer_id").notNull().references(() => observers.id), enteredByObserverId: integer("entered_by_observer_id").references(() => observers.id), distanceType: text("distance_type").notNull(), angle: real("angle").notNull(),
  nMin: integer("n_min").notNull(), nMax: integer("n_max").notNull(), nOptim: integer("n_optim").notNull(), speciesId: integer("species_id").notNull().references(() => species.id), response: text("response").notNull(),
  latitude: real("latitude").notNull(), longitude: real("longitude").notNull(), gpsAccuracy: real("gps_accuracy"), hasPhotos: integer("has_photos", { mode: "boolean" }).notNull().default(false), photoKeys: text("photo_keys").notNull().default("[]"),
  platform: text("platform").notNull(), surveyCode: text("survey_code").notNull().default(""), beaufortSeaState: integer("beaufort_sea_state").notNull().default(1), visibilityScale: integer("visibility_scale").notNull().default(0), douglasSeaState: integer("douglas_sea_state").notNull().default(0), observedAt: text("observed_at").notNull(), comments: text("comments").notNull().default(""), createdAt: text("created_at").notNull().default(sql`CURRENT_TIMESTAMP`),
}, (t) => [index("idx_sightings_observed_at").on(t.observedAt), index("idx_sightings_observer_id").on(t.observerId), index("idx_sightings_entered_by_observer_id").on(t.enteredByObserverId), index("idx_sightings_species_id").on(t.speciesId)]);
